forge "http://forge.puppetlabs.com"
mod 'stdlib', :git => 'git://github.com/puphpet/puppetlabs-stdlib.git'
mod 'concat', :git => 'git://github.com/puphpet/puppetlabs-concat.git'
mod 'apt', :git => 'git://github.com/puphpet/puppetlabs-apt.git'
mod 'yum', :git => 'git://github.com/puphpet/puppet-yum.git'
mod 'vcsrepo', :git => 'git://github.com/puphpet/puppetlabs-vcsrepo.git'
mod 'ntp', :git => 'git://github.com/puphpet/puppetlabs-ntp.git'
mod 'iptables', :git => 'git://github.com/puphpet/puppet-iptables.git'
